name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-clojure:

    strategy:
      matrix:
        java-version: [8, 11]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Print java version
        run: java -version

      - name: Install dependencies
        run: lein deps

      - name: Run clj tests
        run: lein test
