name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-clojure:

    strategy:
      matrix:
        java-version: [11, 17, 21]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          lein: 2.9.1

      - name: Cache Clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('project.clj') }}

      - name: Print Java version
        run: java -version

      - name: Install dependencies
        run: lein deps

      - name: Run clj tests
        run: lein test
