name: Release

on:
  push:
    tags:
    - '*'

jobs:
  test-clojure:
    strategy:
      matrix:
        java-version: [11, 17, 21]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Print java version
        run: java -version

      - name: Install dependencies
        run: lein deps

      - name: Run clj tests
        run: lein test

  release:
    name: 'Publish on Clojars'
    runs-on: ubuntu-latest
    needs: [test-clojure]
    steps:
    - uses: actions/checkout@v4.2.2

    - name: Install dependencies
      run: lein deps

    - name: Publish on Clojars
      run: lein deploy publish
      env:
          CLOJARS_USERNAME: eng-prod-nubank
          CLOJARS_PASSWD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
